hms_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),


    path('user_auth/', include('user_auth.urls')),
    path('hotel/', include('hotel.urls')),



    path("ckeditor5/", include('django_ckeditor_5.urls'))
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path
from . import views

app_name = 'hotel'

urlpatterns = [
    path('', views.Index, name='index')
]

user_auth/urls.py
from django.urls import path
from . import views

app_name = 'user_auth'

urlpatterns = [
    path('sign-up/', views.RegisterView, name='sign-up'),
    path('login/', views.LoginView, name='login'),
    path('logout/', views.Logout, name='logout'),
]

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="codepixer">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>HMS System Hotel{% block title %}{% endblock  %}</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet"> 
        <!--
        CSS
        ============================================= -->
        <link rel="stylesheet" href="{% static "css/linearicons.css" %}">
        <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
        <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
        <link rel="stylesheet" href="{% static "css/nice-select.css" %}">					
        <link rel="stylesheet" href="{% static "css/animate.min.css" %}">
        <link rel="stylesheet" href="{% static "css/owl.carousel.css" %}">
        <link rel="stylesheet" href="{% static "css/main.css" %}">
        <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.11.1/dist/sweetalert2.min.css" rel="stylesheet">

        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        
    </head>
    <body>

        {% include "partials/header.html" %}
        {% block content %}
        
        
        
        {% endblock  %}

        {% include "partials/footer.html" %}

        <script>
            {% for message in messages %}
            Swal.fire({
                icon:"{{message.tags}}",
                title:"{{message}}",
                time:1500
              })
            {% endfor %}
        </script>



		<script src="{% static "js/vendor/jquery-2.2.4.min.js" %}"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="{% static "js/vendor/bootstrap.min.js" %}"></script>			
		<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
  		<script src="{% static "js/easing.min.js" %}"></script>			
		<script src="{% static "js/hoverIntent.js" %}"></script>
		<script src="{% static "js/superfish.min.js" %}"></script>	
		<script src="{% static "js/jquery.ajaxchimp.min.js" %}"></script>
		<script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>	
		<script src="{% static "js/owl.carousel.min.js" %}"></script>			
		<script src="{% static "js/jquery.sticky.js" %}"></script>
		<script src="{% static "js/jquery.nice-select.min.js" %}"></script>			
		<script src="{% static "js/parallax.min.js" %}"></script>		
		<script src="{% static "js/mail-script.js" %}"></script>	
		<script src="{% static "js/main.js" %}"></script>	
    </body>
</html>

templates/partials/footer.html
{% load static %}

            <!--Start Footer-->
            <footer class="footer-area section-gap">
                <div class="container">
                    <div class='row'>
                        <div class="col-lg-3  col-md-12">
							<div class="single-footer-widget">
								<h6>Top Products</h6>
								<ul class="footer-nav">
									<li><a href="#">Managed Website</a></li>
									<li><a href="#">Manage Reputation</a></li>
									<li><a href="#">Power Tools</a></li>
									<li><a href="#">Marketing Service</a></li>
								</ul>
							</div>
						</div>

                        <div class="col-lg-6  col-md-12">
							<div class="single-footer-widget newsletter">
								<h6>Newsletter</h6>
								<p>You can trust us. we only send promo offers, not a single spam.</p>
								<div id="mc_embed_signup">
									<form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="form-inline">

										<div class="form-group row" style="width: 100%">
											<div class="col-lg-8 col-md-12">
												<input name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '" required="" type="email">
												<div style="position: absolute; left: -5000px;">
													<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
												</div>
											</div> 
										
											<div class="col-lg-4 col-md-12">
												<button class="nw-btn primary-btn">Subscribe<span class="lnr lnr-arrow-right"></span></button>
											</div> 
										</div>		
										<div class="info"></div>
									</form>
								</div>		
							</div>
						</div>

                        <div class="col-lg-3  col-md-12">
							<div class="single-footer-widget mail-chimp">
								<h6 class="mb-20">Instragram Feed</h6>
								<ul class="instafeed d-flex flex-wrap">
									<li><img src="{% static "img/i1.jpg" %}" alt=""></li>
									<li><img src="{% static "img/i2.jpg" %}" alt=""></li>
									<li><img src="{% static "img/i3.jpg" %}" alt=""></li>
									<li><img src="{% static "img/i4.jpg" %}" alt=""></li>
									<li><img src="{% static "img/i5.jpg" %}" alt=""></li>
									<li><img src="{% static "img/i6.jpg" %}" alt=""></li>
									<li><img src="{% static "img/i7.jpg" %}" alt=""></li>
									<li><img src="{% static "img/i8.jpg" %}" alt=""></li>
								</ul>
							</div>
						</div>

                    </div>

                    <div class="row footer-bottom d-flex justify-content-between">
						<p class="col-lg-8 col-sm-12 footer-text m-0 text-white">
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>
						<div class="col-lg-4 col-sm-12 footer-social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
                </div>
            </footer>
             <!--End Footer-->
		

templates/partials/header.html
{% load static %}

<header id="header" id="home">
    <div class="container">
        <div class="row align-items-center justify-content-between d-flex">
          <div id="logo">
            <a href="{% url "hotel:index" %}"><img src="{% static "img/logo.png" %}" alt="" title="" /></a>
          </div>
          <nav id="nav-menu-container">
            <ul class="nav-menu">
              <li class="menu-active"><a href="{% url "hotel:index" %}">Home</a></li>
              <li><a href="about-us.html">About Us</a></li>
              <li><a href="category.html">Category</a></li>
              <li><a href="price.html">Price</a></li>
              <li><a href="blog-home.html">Blog</a></li>
              <li><a href="contact.html">Contact</a></li>
              <li class="menu-has-children"><a href="">Pages</a>
                <ul>
                    <li><a href="elements.html">elements</a></li>
                    <li><a href="search.html">search</a></li>
                    <li><a href="single.html">single</a></li>
                </ul>
              </li>

              {% if user.is_authenticated %}
              <li><a class="ticker-btn" href="">Dashboard</a></li>
                <li><a class="ticker-btn" href="{% url "user_auth:logout" %}">Logout</a></li>
              {% else %}
                <li><a class="ticker-btn" href="{% url "user_auth:sign-up" %}">Signup</a></li>
                <li><a class="ticker-btn" href="{% url "user_auth:login" %}">Login</a></li>
              {% endif %}
              
            </ul>
          </nav><!-- #nav-menu-container -->		    		
        </div>
    </div>
</header>